Models/Entites/Color.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMST4.Store.Shoes.Models.Entites
{
    public class Color
    {
        public Guid Id { get; set; }
        public string Description { get; set; }
        public DateTime CreatedBy { get; set; }
    }
}

Models/Entites/Product.cs
namespace AMST4.Store.Shoes.Models.Entites;

    public class Product
    {
        public Guid Id { get; set; }
        public string Brand { get; set; } = string.Empty;
        public Guid ColorId { get; set; }
        public Guid SizeId { get; set; }
        public double Price { get; set; }
        public string Description { get; set; } = string.Empty;
        public double Stock  { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedBy { get; set; }


    }

Models/Entites/Size.cs
namespace AMST4.Store.Shoes.Models.Entites
{
    public class Size
    {
        public Guid Id { get; set; }
        public string Description { get; set; }
        public DateTime CreatedBy { get; set; }  
    }
}

Models/ErrorViewModel.cs
namespace AMST4.Store.Shoes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;

namespace AMST4.Store.Shoes.Controllers;

public class ColorController : Controller
{
    [HttpGet]
    public ActionResult ColorIndex()
    {
        return View();
    }

    [HttpGet]
    public ActionResult Cadastre()
    {
        return View();
    }


}

Controllers/HomeController.cs
using AMST4.Store.Shoes.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AMST4.Store.Shoes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Color/Cadastre.cshtml
    <style>
        body {
            background-color: #f4f4f4;
            font-family: 'Segoe UI', sans-serif;
        }

        .card-custom {
            background: linear-gradient(45deg, #6ab1d7 0%, #3383cd 100%);
            border: none;
            color: white;
        }

        .card-header-custom {
            background-color: #fff;
            color: #333;
            font-size: 1.5rem;
            text-align: center;
        }

        .search-bar {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .search-input {
            flex-grow: 1;
        }

        .img-fluid {
            max-width: 100%;
            height: auto;
        }

        .btn-custom {
            background-color: #28a745;
            border-color: #28a745;
        }

            .btn-custom:hover {
                background-color: #218838;
                border-color: #1e7e34;
            }

        .btn-outline-custom {
            border-color: #007bff;
            color: #007bff;
        }

            .btn-outline-custom:hover {
                background-color: #007bff;
                color: #fff;
            }

    </style>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card card-custom rounded">
                    <div class="card-header card-header-custom">Cadastre Sua Cor</div>
                    <div class="card-body">
                        <h3 class="fs-4">Descrição</h3>
                        <input type="text" class="form-control mb-3" placeholder="Insira a Descrição Da Sua Cor" />
                        <button type="button" class="btn btn-custom">Adicionar</button>
                    </div>
                </div>
            </div>
            <div class="col-md-4 d-flex align-items-start justify-content-end">
                <div class="input-group mb-3 gap-2">
                   
                    <img src="~/img/cromatico.png" class="img-fluid" alt="Imagem Cromática" />
                    <a asp-controller="Color" asp-action="Cadastre" type="button" class="btn btn-outline-primary btnAdd w-100">Voltar</a>
                </div>
            </div>
        </div>
    </div>

   

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1 class="display-4">BEM VINDO(A) à Loja Power Sapatos</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
        
            <img src="~/img/ShooteIndex.jpg" class="img-fluid rounded" alt="Shoe Store Image">
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AMST4.Store.Shoes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AMST4.Store.Shoes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AMST4.Store.Shoes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Color" asp-action="ColorIndex">Cadastro De Cor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-light">
        <div class="container">
            &copy; 2024 - AMST4.Store.Shoes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>